### PR TITLE
Fixed show title

### LINKED ISSUE #40: No Title in Command Prompt
Screenshot (5)

The show title used to appear before the season and episode number. The problem with this no longer being the case is that I can't skip episodes I already have anymore. I've tried to rename the files with spaces in front (as there seems to be a space in place of the missing title), but that doesn't seem to work. Any help would be appreciated.

### PR DESCRIPTION
**Pull request by turtletowerz**
This is a simple fix for the title not showing, which should fix #40

### CODE REVIEW

**Comment by turtletowerz** [comment]
The second commit removes the old method for dependencies and replaces it with [Go's New Module System](https://github.com/golang/go/wiki/Modules). This is a pretty big change so if you'd like me to just ship the title fix separately then I'll close this pull request and open a new one. I just thought it would be a good opportunity to update this because it reduces the clutter while still maintaining functionality.

**Comment by s32x** [comment]
Nah that's fine if they're both together. I see both commits. However, could we keep the vendor folder in the repo? I think all you'd need to run is `go mod vendor` go pull them all in. Just commit those and I'm happy to merge this. Thanks a lot for taking care of this!

**Comment by turtletowerz** [comment]
Alright I've added back the vendor files.

**Comment by s32x** [comment]
Hmm, I see your commit with the vendor files but the PR still shows -388,960 removals. Weird I guess github can't keep up. Anyway, Thanks for taking care of this bug!! I really appreciate it.

**Pull request merged**
